name: React Portfolio

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_test_deploy:
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.18.11

      - name: Install Dependencies
        run: |
          npm ci

      # - name: Build
      #   run: |
      #     npm run build

      # - name: Test
      #   run: |
      #     yarn test

      - name: Deploy
        run: |
          npm run deploy
